### ISSUE TITLE
Running IRIS with SLURM

### ISSUE THREAD

**Issue by p-levy** [Xinglab/IRIS#3]
Hi Yang and Eric, 

I tried to run the pipeline (just the `./run_example` script) on our server but got the following error at the `prediction` step. 
```
FileNotFoundError: [Errno 2] No such file or directory: 'qsub': 'qsub'
```
I guess it's because our server doesn't have SGE but uses SLURM. Is there a way to run IRIS without using SGE? 

Thank you!
Pierre

**Comment by EricKutschera** [comment]
The code was originally written for a server with SGE and it tries to use qsub to run the prediction step. I was able to get `./run_example` to work on a server with SLURM by editing the script that submits and checks the status of the jobs. I also updated some of the version numbers for installing dependencies since I was seeing some errors during my initial attempt to install. Here is the commit with the code changes: https://github.com/Xinglab/IRIS/commit/35900d657b977c77a6c5a16fd586c28cf38c2bc7
