### ISSUE TITLE
Run IRIS on hg38

### ISSUE THREAD

**Issue by mguaita** [Xinglab/IRIS#7]
Hello,

As seen in the methods section of the paper the IRIS RNA-seq data processing uses the reference human genome hg19.
Is it possible to use IRIS with the reference human genome hg38?

Also, can the IRIS functions be run individually one by one without configuring the snakemake files?

Thank you,

**Comment by ypnngaa-py** [comment]
Hi Maria,

We recommend using hg19 with IRIS because it has not been tested with hg38.
Certain key components and steps in IRIS, such as pre-calculated databases,
translation steps, and the prediction of CAR-T targets, are based on hg19.

You can run individual IRIS functions without using the full snakemake.
Feel free to refer to the help manual (-h) of each function and the
arguments used in the snakemake pipeline to build your own pipeline.


Yang

**Comment by mguaita** [comment]
Hello Yang, 

Thank you very much for the early reply!
And, are you planning to update the pre-calculated databases and predictors to the hg38 reference?

Maria
